# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440469e1bbe8f0905ab9f1de631689230bfa36256928abc3b407c8378bb2cb5a2b8c743bfece525c25f5c877bf17ed951403acb58645554068420c4015834ed0

test:
  secret_key_base: 4f3a79e60d848edbc1f76ea1333dc23f7e9544be8aa499de7874361887eda090281edd0cc06673ff0903ab9434008ad90218fa1eca953453c5717e89b422a628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
